name: CI Simple (Shell)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar script Shell
        run: |
          echo "Hola desde Shell"
          echo "Workflow ejecutado correctamente"
